# site settings
title: Shlhnj
subtitle: 
email: mail.shulhan@gmail.com
description: An aspiring cartographer and ecological modeller, <br /> Still learning to code.
baseurl: "/portofolio" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Timoho 1
city: Semarang
state: Central Java
zip_code: 50275
country: Indonesia
phone: (+62) 089 829 09 751

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  researchgate: https://www.researchgate.net/profile/Muhammad-Jihadi-2
  orcid: https://orcid.org/0009-0003-7193-7298
  Instagram: https://www.instagram.com/shlhn._/
  LinkedIn: https://www.linkedin.com/in/mshulhanj
  Twitter: https://twitter.com/shlhnj
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
